### ISSUE TITLE
Support docker labels

### ISSUE THREAD

**Issue by blindrood** [lfdominguez/docker_log_driver_loki#2]
Would be great to have support for docker labels:
e.g.
`docker run -d --label name=test whatever_image:latest`
should work fine and loki should understand label name with value test
Currently it throws error
`docker: Error response from daemon: failed to initialize logging driver: error creating logger: error in one of the logger options: wrong log-opt: 'labels'`

Thanks for great work btw

**Comment by lfdominguez** [comment]
Can you showme the options that you pass to the logger?

**Comment by blindrood** [comment]
All I did was put loki-host and loki-port pointing to my loki instance

**Comment by lfdominguez** [comment]
ok
